version: 2.1

jobs:
  build-ios:
    macos:
      xcode: 16.2.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: "Install mise and Tuist"
          command: |
            cd Hedge
            curl https://mise.run | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            echo 'eval "$(/Users/distiller/.local/bin/mise activate bash)"' >> $BASH_ENV
            source $BASH_ENV
            mise use tuist@latest
      - run:
          name: "Install dependencies"
          command: |
            cd Hedge
            tuist install
      - run:
          name: "Generate Xcode project"
          command: |
            cd Hedge
            tuist generate
#      - run:
#          name: "Build project"
#          command: |
#            cd Hedge
#            xcodebuild -workspace Hedge.xcworkspace -scheme Hedge -destination 'platform=iOS Simulator,name=iPhone 15' build

workflows:
  ios-ci-workflow:
    jobs:
      - build-ios
