version: 2.1

jobs:
  build-ios:
    macos:
      xcode: 16.4.0
    steps:
      - checkout
      - run:
          name: "Install Tuist"
          command: |
            cd Sample
            curl -Ls https://install.tuist.io | bash
      - run:
          name: "Generate Xcode project"
          command: |
            cd Sample
            tuist generate
      - run:
          name: "Build project"
          command: |
            cd Sample
            xcodebuild -workspace Sample.xcworkspace -scheme Sample -destination 'platform=iOS Simulator,name=iPhone 15' build

workflows:
  ios-ci-workflow:
    jobs:
      - build-ios:
          filters:
            branches:
              only: 
                - main
                - /feature\/IC-12\/.*/
